name: MIC-file-converter
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - icu=73.1=h6c2663c_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jpeg=9e=h827c3e9_3
  - krb5=1.20.1=h5b6d351_0
  - lerc=4.0.0=h5da7b33_0
  - libclang=14.0.6=default_hb5a9fac_2
  - libclang13=14.0.6=default_h8e68704_2
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libtiff=4.5.1=h44ae7cf_1
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - numpy=2.2.2=py310h055cbcc_0
  - numpy-base=2.2.2=py310h65a83cf_0
  - openssl=3.0.16=h3f729d1_0
  - packaging=24.2=py310haa95532_0
  - pip=25.0=py310haa95532_0
  - ply=3.11=py310haa95532_0
  - pyqt=6.7.1=py310h5da7b33_0
  - pyqt5-sip=12.13.0=py310h827c3e9_1
  - pyqt6-sip=13.9.1=py310h827c3e9_0
  - python=3.10.16=h4607a30_1
  - qt-main=6.7.2=haa95532_0
  - qt5compat=6.7.2=hda331cc_0
  - qtbase=6.7.2=h0804d20_1
  - qtdeclarative=6.7.2=h5da7b33_0
  - qtimageformats=6.7.2=h0324649_0
  - qtpy=2.4.1=py310haa95532_0
  - qtshadertools=6.7.2=h5da7b33_0
  - qtsvg=6.7.2=hf2fb9eb_0
  - qttools=6.7.2=h0de5f00_0
  - qttranslations=6.7.2=h5da7b33_0
  - qtwebchannel=6.7.2=h5da7b33_0
  - qtwebsockets=6.7.2=h5da7b33_0
  - setuptools=72.1.0=py310haa95532_0
  - sip=6.10.0=py310h5da7b33_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - tomli=2.0.1=py310haa95532_0
  - vc=14.42=haa95532_4
  - vs2015_runtime=14.42.34433=he0abc0d_4
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - pandas==2.2.3
      - pillow==11.1.0
      - ptufile==2025.2.20
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - six==1.17.0
      - tifffile==2025.2.18
      - tzdata==2025.1
      - xarray==2025.1.2
prefix: C:\Users\Nikon\miniconda3\envs\MIC-file-converter
